/**
 * Polish speech. Fixed course text (words, sentences, dialogues, phrases) is pre-recorded with a neural
 * Polish voice (Piper, generated by scripts/voice.py) and served as small MP3s from /voice/. Anything else,
 * such as a number typed into the tools, uses the browser's built-in pl-PL voice, as does everything when
 * the learner prefers their device's voice. With neither available, speak() is a no-op and the UI shows
 * spelling-based pronunciation guidance instead.
 */

let voice: SpeechSynthesisVoice | null = null;
let ready = false;
const listeners = new Set<() => void>();

function pickVoice() {
  if (typeof speechSynthesis === 'undefined') return;
  let voices: SpeechSynthesisVoice[] = [];
  try {
    voices = speechSynthesis.getVoices();
  } catch {
    // Privacy browsers (Brave, some iOS modes) can refuse voice lists; lessons fall back to spelling help.
  }
  const polish = voices.filter((v) => v.lang.toLowerCase().replace('_', '-').startsWith('pl'));
  // Prefer higher-quality network/"natural" voices where the platform offers them.
  voice = polish.find((v) => /natural|enhanced|premium|google/i.test(v.name)) ?? polish[0] ?? null;
  ready = true;
  listeners.forEach((l) => l());
}

// Runs at import time, so a browser that blocks speech must never stop the whole app from starting.
try {
  if (typeof speechSynthesis !== 'undefined') {
    pickVoice();
    speechSynthesis.addEventListener?.('voiceschanged', pickVoice);
  }
} catch {
  ready = true;
}

/* ---------- Recorded voice ---------- */

/** Which recordings exist: public/voice-index.json, written by scripts/voice.py. */
interface VoiceIndex {
  /** Folder under /voice/ for this voice and its settings. */
  voice: string;
  ids: Set<string>;
}

let recorded: VoiceIndex | null = null;
let preferDevice = false;

/**
 * A recording's file name: a 53-bit string hash (cyrb53) of the text, in base 36. The same function names the
 * files when they are generated (scripts/spoken-list.ts), so no text-to-file table has to be downloaded.
 */
export function audioId(text: string): string {
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 2654435761);
    h2 = Math.imul(h2 ^ c, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(36);
}

/** The form of a text a recording is made from and looked up by: what speak() says, in Unicode NFC. */
export const audioKey = (text: string) => speakable(text).normalize('NFC');

async function loadVoiceIndex() {
  try {
    const res = await fetch('/voice-index.json');
    if (!res.ok) return;
    const data = (await res.json()) as { voice: string; ids: string[] };
    recorded = { voice: data.voice, ids: new Set(data.ids) };
    listeners.forEach((l) => l());
  } catch {
    // Offline before the index was ever fetched: the device voice covers it.
  }
}

if (typeof window !== 'undefined' && typeof fetch === 'function') void loadVoiceIndex();

/** Use the device's own voice even for recorded text (a setting). */
export function setPreferDeviceVoice(on: boolean) {
  if (preferDevice === on) return;
  preferDevice = on;
  listeners.forEach((l) => l());
}

const recordingOf = (text: string): string | null => {
  if (!recorded || preferDevice) return null;
  const id = audioId(audioKey(text));
  return recorded.ids.has(id) ? `/voice/${recorded.voice}/${id}.mp3` : null;
};

export const hasRecording = (text: string) => recordingOf(text) !== null;
export const recordingsAvailable = () => recorded !== null && !preferDevice;

export const speechSupported = () => typeof speechSynthesis !== 'undefined';
/** Whether any Polish can be spoken: recordings or a device voice. */
export const hasPolishVoice = () => voice !== null || recordingsAvailable();
/** Whether this particular text can be spoken. */
export const canSpeak = (text: string) => voice !== null || hasRecording(text);
export const hasDeviceVoice = () => voice !== null;
export const voicesReady = () => ready;

export function onVoicesChanged(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

let rate = 0.9;
export const setSpeechRate = (r: number) => {
  rate = r;
};

/**
 * The part of a prompt that should be read aloud. English glosses in brackets, gaps, the slash between
 * spelling alternatives and a figure before "=" are for the eye only: a filled-in "woda (water)" is read
 * as "woda", and "20 = dwadzieścia" as "dwadzieścia".
 */
export function speakable(text: string): string {
  return text
    .replace(/^[^=]*=\s*/, '')
    .replace(/\s*\([^)]*\)/g, '')
    .replace(/_{2,}/g, '')
    .replace(/\s+\/\s+/g, ', ')
    .replace(/\s+/g, ' ')
    .replace(/ ([.,!?])/g, '$1')
    .trim();
}

/** The speed setting is tuned for synthetic voices, where 0.9 is the default; recordings play at 1× there. */
const DEFAULT_RATE = 0.9;
const speedOf = (slow?: boolean) => (slow ? Math.max(0.5, rate * 0.65) : rate);

let playing: HTMLAudioElement | null = null;

/** Stop whatever is being read aloud. */
export function stopSpeaking() {
  if (playing) {
    playing.onended = playing.onerror = null;
    playing.pause();
    playing = null;
  }
  try {
    if (speechSupported()) speechSynthesis.cancel();
  } catch {
    // Nothing was speaking.
  }
}

/**
 * Recordings are made slightly slower than natural speech (see scripts/voice.py). `natural` plays them, and the
 * device voice, at the pace Poles actually talk, whatever the speed setting: for listening practice.
 */
const NATURAL = 1.08;

export function speak(text: string, opts: { slow?: boolean; natural?: boolean; onEnd?: () => void } = {}): void {
  text = speakable(text);
  if (!text) {
    opts.onEnd?.();
    return;
  }
  stopSpeaking();
  const src = recordingOf(text);
  if (src && typeof Audio !== 'undefined') {
    const audio = new Audio(src);
    playing = audio;
    audio.playbackRate = opts.natural ? NATURAL : Math.min(2, Math.max(0.5, speedOf(opts.slow) / DEFAULT_RATE));
    audio.preservesPitch = true;
    audio.onended = () => {
      if (playing === audio) playing = null;
      opts.onEnd?.();
    };
    // A missing or broken file falls back to the device voice.
    audio.onerror = () => {
      if (playing === audio) playing = null;
      speakWithDevice(text, opts);
    };
    audio.play().catch((e: unknown) => {
      // Autoplay before the learner has touched the page is blocked for every kind of audio: wait for a tap.
      if (e instanceof DOMException && e.name === 'NotAllowedError') opts.onEnd?.();
    });
    return;
  }
  speakWithDevice(text, opts);
}

function speakWithDevice(text: string, opts: { slow?: boolean; natural?: boolean; onEnd?: () => void }) {
  if (!speechSupported() || !voice) {
    opts.onEnd?.();
    return;
  }
  try {
    speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.voice = voice;
    u.lang = voice.lang;
    u.rate = opts.natural ? 1 : speedOf(opts.slow);
    u.onend = () => opts.onEnd?.();
    u.onerror = () => opts.onEnd?.();
    speechSynthesis.speak(u);
  } catch {
    opts.onEnd?.();
  }
}
